default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: local
    hooks:
      - id: biome
        name: biome
        entry: pnpm exec biome check
        language: system
        files: '\\.(?:[cm]?js|[cm]?ts|json)$'
        pass_filenames: true
